//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD
    {
        public string So_HoaD { get; set; }
        public string So_P { get; set; }
        public Nullable<int> TienP { get; set; }
        public Nullable<int> TienD { get; set; }
        public Nullable<int> TienN { get; set; }
        public Nullable<System.DateTime> NgayG { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
