//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string Ma_HD { get; set; }
        public string Ma_SV { get; set; }
        public string Ma_NV { get; set; }
        public string So_P { get; set; }
        public Nullable<System.DateTime> NgayL { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual SV SV { get; set; }
    }
}
