//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HopDongs = new HashSet<HopDong>();
            this.Khus = new HashSet<Khu>();
        }
    
        public string Ma_NV { get; set; }
        public string Ma_TK { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NSinh { get; set; }
        public Nullable<bool> GTinh { get; set; }
        public string DiaChi { get; set; }
        public string ChucVu { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khu> Khus { get; set; }
        public virtual Login Login { get; set; }
    }
}
