//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SV()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public string Ma_SV { get; set; }
        public string Ma_TK { get; set; }
        public string Ho_Ten { get; set; }
        public Nullable<System.DateTime> NS { get; set; }
        public Nullable<bool> GT { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string Dia_Chi { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual Login Login { get; set; }
    }
}
